# Generated by Django 4.0.4 on 2022-05-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaires', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('numero_commande', models.IntegerField(blank=True, null=True, verbose_name='Numero Commnande')),
                ('date_commande', models.DateField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Nom')),
                ('ligne_un', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Ligne 1')),
                ('ligne_un_qte', models.IntegerField(blank=True, default='0', null=True, verbose_name='Quantite')),
                ('ligne_un_prix_unitaire', models.IntegerField(blank=True, default='0', null=True, verbose_name='Prix Unitaire (D)')),
                ('ligne_un_prix_total', models.IntegerField(blank=True, default='0', null=True, verbose_name='Ligne Total (D)')),
                ('ligne_deux', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Ligne 2')),
                ('ligne_deux_qte', models.IntegerField(blank=True, default='0', null=True, verbose_name='Quantite')),
                ('ligne_deux_prix_unitaire', models.IntegerField(blank=True, default='0', null=True, verbose_name='Prix Unitaire (D)')),
                ('ligne_deux_prix_total', models.IntegerField(blank=True, default='0', null=True, verbose_name='Ligne Total (D)')),
                ('ligne_trois', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Ligne 3')),
                ('ligne_trois_qte', models.IntegerField(blank=True, default='0', null=True, verbose_name='Quantite')),
                ('ligne_trois_prix_unitaire', models.IntegerField(blank=True, default='0', null=True, verbose_name='Prix Unitaire (D)')),
                ('ligne_trois_prix_total', models.IntegerField(blank=True, default='0', null=True, verbose_name='Ligne Total (D)')),
                ('ligne_quatre', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Ligne 4')),
                ('ligne_quatre_qte', models.IntegerField(blank=True, default='0', null=True, verbose_name='Quantite')),
                ('ligne_quatre_prix_unitaire', models.IntegerField(blank=True, default='0', null=True, verbose_name='Prix Unitaire (D)')),
                ('ligne_quatre_prix_total', models.IntegerField(blank=True, default='0', null=True, verbose_name='Ligne Total (D)')),
                ('ligne_cinq', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Ligne 5')),
                ('ligne_cinq_qte', models.IntegerField(blank=True, default='0', null=True, verbose_name='Quantite')),
                ('ligne_cinq_prix_unitaire', models.IntegerField(blank=True, default='0', null=True, verbose_name='Prix Unitaire (D)')),
                ('ligne_cinq_prix_total', models.IntegerField(blank=True, default='0', null=True, verbose_name='Ligne Total (D)')),
                ('phone', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='phone')),
                ('total', models.IntegerField(blank=True, default='0', null=True, verbose_name='Total')),
                ('balance', models.IntegerField(blank=True, default=0, null=True, verbose_name='balance')),
                ('creer', models.DateTimeField(auto_now_add=True)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('Paie', models.BooleanField(default=False)),
                ('type_commande', models.CharField(blank=True, choices=[('Reception', 'Reception'), ('Proforma', 'Proforma'), ('Commande', 'Commande')], default='', max_length=50, null=True)),
            ],
        ),
    ]
